[project]
name = "transformer"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "numpy>=2.2.6",
    "pre-commit>=4.2.0",
    "ruff>=0.11.11",
    "torch==2.5.1",
]
